version: '3'

volumes:
  mongo-data:

networks:
  fastfood-network:
    name: fastfood_network

services:
  app:
    image: fastfood
    build: .
    container_name: app-fastfood
    hostname: app-fastfood
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    depends_on:
      - db
    networks:
      - fastfood-network

  db:
    image: mongo:4.4.14
    restart: unless-stopped
    container_name: $MONGODB_CONTAINER_NAME
    hostname: $MONGODB_HOST_NAME
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./mongo-data:/data/db
    networks:
      - fastfood-network